export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REM_INGREDIENT='REM_INGREDIENT';
export const SET_INITIAL_INGREDIENTS='SET_INITIAL_INGREDIENTS';
export const FETCHING_INGREDIENTS_FAILD='FETCHING_INGREDIENTS_FAILD'

//post order data to firebase action
export const PURCHASE_BURGER_START='PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAILD='PURCHASE_BURGER_FAILD'

//dispatches when we load checkout page
export const PURCHASE_INIT='PURCHASE_INIT'

//login
export const AUTH_START='AUTH_START'
export const AUTH_SUCCESS='AUTH_SUCCESS'
export const AUTH_FAIL='AUTH_FAIL'
export const USER_AUTH_EXPIRES='USER_AUTH_EXPIRES'